server:
  port: 4444

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: update
          uri: lb://CLIENT-UPDATER
          predicates:
            - Path=/api/update/**
        - id: update
          uri: lb://client-updater
          predicates:
            - Path=/api/update/**